name: Cleanup Old Files

on:
  schedule:
    # kas 12 valandų
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run cleanup script
        run: |
          python dailycleanup.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add downloads/ csv/

          git diff --cached --quiet || git commit -m "Cleanup old files (keep latest 15)"

          git push
